---
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    app: kronos
  name: kronos
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kronos
      name: kronos
    spec:
      containers:
      - command:
        - /bin/entrypoint.sh
        env:
        - name: AWS_KRONOS_BUCKET
          value: tusharma-kronos-data
        - name: AWS_GNOSIS_BUCKET
          value: tusharma-gnosis-data
        - name: AWS_SOFTNET_BUCKET
          value: tusharma-softnet-data
        - name: DEPLOYMENT_PREFIX
          value: DEV
        - name: SERVICE_PORT
          value: "6006"
        - name: SERVICE_TIMEOUT
          value: "900"
        - name: AWS_S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_S3_ACCESS_KEY_ID
              name: aws-stack-analysis
        - name: AWS_S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_S3_SECRET_ACCESS_KEY
              name: aws-stack-analysis
        image: surajd/kronos:latest
        ports:
        - containerPort: 6006
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 6006
          initialDelaySeconds: 2
          timeoutSeconds: 15
        name: kronos
        readinessProbe:
          httpGet:
            path: /
            port: 6006
          initialDelaySeconds: 2
          timeoutSeconds: 15
        resources:
          requests:
            cpu: "4"
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kronos
  name: kronos
spec:
  ports:
  - port: 6006
    targetPort: 0
  selector:
    app: kronos
---
apiVersion: v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: kronos
  name: kronos
spec:
  host: ""
  port:
    targetPort: 6006
  to:
    kind: Service
    name: kronos
    weight: null

